[project]
name = "delivery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aio-pika>=9.5.8",
    "fastapi[standard]>=0.123.5",
    "psycopg[binary]>=3.3.1",
    "sqlmodel>=0.0.27",
]
